apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab
  namespace: {{ .Values.namespace }}
spec:
  description: Lab 4 GitOps workspace
  sourceRepos:
    - 'https://gitea.{{ .Values.deployer.domain }}/*'
  destinations:
    - namespace: {{ .Values.gitopsLab.namespace }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
