---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasphere-pipeline-workspace
  namespace: {{ .Values.datasphere.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pipeline.pvc.storageSize }}
  storageClassName: {{ .Values.pipeline.pvc.storageClass | default "ocs-external-storagecluster-cephfs" }}
