apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: datasphere-lab
spec:
  name: {{ .Values.displayName | quote }}
  description: {{ .Values.description | quote }}
  connectionConfig:
    url: {{ .Values.repoURL | quote }}
