apiVersion: v1
kind: ConfigMap
metadata:
  name: datasphere-config
data:
  config.json: |
    {"theme": "{{ .Values.theme }}"}
  extra_datacenters.json: |
    {{ .Values.api.extraDatacenters | toJson }}
