apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: datasphere-ui
  labels:
    app: datasphere
    component: ui
spec:
  to:
    kind: Service
    name: datasphere-ui
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
