DATACENTERS = [
    # ── MAJOR HUBS (Red Hat branded) ────────────────────────────────────────
    {
        "id": "rh-us-east",
        "display_name": "US East",
        "city": "Virginia",
        "region": "Americas",
        "tier": "major",
        "lat": 37.4,
        "lng": -78.6,
        "base_capacity_pct": 62,
        "base_workload_count": 1847,
    },
    {
        "id": "rh-us-west",
        "display_name": "US West",
        "city": "Oregon",
        "region": "Americas",
        "tier": "major",
        "lat": 44.0,
        "lng": -120.5,
        "base_capacity_pct": 48,
        "base_workload_count": 1203,
    },
    {
        "id": "rh-eu-central",
        "display_name": "EU Central",
        "city": "Frankfurt",
        "region": "Europe",
        "tier": "major",
        "lat": 50.1,
        "lng": 8.7,
        "base_capacity_pct": 71,
        "base_workload_count": 2156,
    },
    {
        "id": "rh-eu-west",
        "display_name": "EU West",
        "city": "Dublin",
        "region": "Europe",
        "tier": "major",
        "lat": 53.3,
        "lng": -6.2,
        "base_capacity_pct": 55,
        "base_workload_count": 987,
    },
    {
        "id": "rh-apac-ne",
        "display_name": "APAC Northeast",
        "city": "Tokyo",
        "region": "Asia Pacific",
        "tier": "major",
        "lat": 35.7,
        "lng": 139.7,
        "base_capacity_pct": 80,
        "base_workload_count": 2891,
    },
    {
        "id": "rh-apac-se",
        "display_name": "APAC Southeast",
        "city": "Sydney",
        "region": "Asia Pacific",
        "tier": "major",
        "lat": -33.9,
        "lng": 151.2,
        "base_capacity_pct": 41,
        "base_workload_count": 763,
    },

    # ── REGIONAL EDGE SITES ─────────────────────────────────────────────────
    # Americas
    {
        "id": "edge-us-ne",
        "display_name": "US Northeast Edge",
        "city": "New York",
        "region": "Americas",
        "tier": "regional",
        "lat": 40.7,
        "lng": -74.0,
        "base_capacity_pct": 45,
        "base_workload_count": 234,
    },
    {
        "id": "edge-us-south",
        "display_name": "US South Edge",
        "city": "Dallas",
        "region": "Americas",
        "tier": "regional",
        "lat": 32.8,
        "lng": -96.8,
        "base_capacity_pct": 38,
        "base_workload_count": 189,
    },
    {
        "id": "edge-us-central",
        "display_name": "US Central Edge",
        "city": "Chicago",
        "region": "Americas",
        "tier": "regional",
        "lat": 41.9,
        "lng": -87.6,
        "base_capacity_pct": 52,
        "base_workload_count": 301,
    },
    {
        "id": "edge-us-nw",
        "display_name": "US Northwest Edge",
        "city": "Seattle",
        "region": "Americas",
        "tier": "regional",
        "lat": 47.6,
        "lng": -122.3,
        "base_capacity_pct": 29,
        "base_workload_count": 156,
    },
    {
        "id": "edge-ca-east",
        "display_name": "Canada East Edge",
        "city": "Toronto",
        "region": "Americas",
        "tier": "regional",
        "lat": 43.7,
        "lng": -79.4,
        "base_capacity_pct": 33,
        "base_workload_count": 178,
    },
    {
        "id": "edge-ca-west",
        "display_name": "Canada West Edge",
        "city": "Vancouver",
        "region": "Americas",
        "tier": "regional",
        "lat": 49.3,
        "lng": -123.1,
        "base_capacity_pct": 21,
        "base_workload_count": 98,
    },
    {
        "id": "edge-latam-br",
        "display_name": "LATAM Brazil Edge",
        "city": "São Paulo",
        "region": "Americas",
        "tier": "regional",
        "lat": -23.5,
        "lng": -46.6,
        "base_capacity_pct": 44,
        "base_workload_count": 267,
    },
    {
        "id": "edge-latam-mx",
        "display_name": "LATAM Mexico Edge",
        "city": "Mexico City",
        "region": "Americas",
        "tier": "regional",
        "lat": 19.4,
        "lng": -99.1,
        "base_capacity_pct": 36,
        "base_workload_count": 201,
    },
    {
        "id": "edge-latam-ar",
        "display_name": "LATAM South Edge",
        "city": "Buenos Aires",
        "region": "Americas",
        "tier": "regional",
        "lat": -34.6,
        "lng": -58.4,
        "base_capacity_pct": 28,
        "base_workload_count": 134,
    },
    # Europe
    {
        "id": "edge-eu-north",
        "display_name": "EU North Edge",
        "city": "Stockholm",
        "region": "Europe",
        "tier": "regional",
        "lat": 59.3,
        "lng": 18.1,
        "base_capacity_pct": 31,
        "base_workload_count": 167,
    },
    {
        "id": "edge-eu-south",
        "display_name": "EU South Edge",
        "city": "Madrid",
        "region": "Europe",
        "tier": "regional",
        "lat": 40.4,
        "lng": -3.7,
        "base_capacity_pct": 39,
        "base_workload_count": 223,
    },
    {
        "id": "edge-eu-east",
        "display_name": "EU East Edge",
        "city": "Warsaw",
        "region": "Europe",
        "tier": "regional",
        "lat": 52.2,
        "lng": 21.0,
        "base_capacity_pct": 27,
        "base_workload_count": 143,
    },
    {
        "id": "edge-eu-benelux",
        "display_name": "EU Benelux Edge",
        "city": "Amsterdam",
        "region": "Europe",
        "tier": "regional",
        "lat": 52.4,
        "lng": 4.9,
        "base_capacity_pct": 43,
        "base_workload_count": 256,
    },
    {
        "id": "edge-uk-south",
        "display_name": "UK South Edge",
        "city": "London",
        "region": "Europe",
        "tier": "regional",
        "lat": 51.5,
        "lng": -0.1,
        "base_capacity_pct": 37,
        "base_workload_count": 214,
    },
    {
        "id": "edge-eu-italy",
        "display_name": "EU Italy Edge",
        "city": "Milan",
        "region": "Europe",
        "tier": "regional",
        "lat": 45.5,
        "lng": 9.2,
        "base_capacity_pct": 34,
        "base_workload_count": 189,
    },
    {
        "id": "edge-eu-iberia",
        "display_name": "EU Iberia Edge",
        "city": "Lisbon",
        "region": "Europe",
        "tier": "regional",
        "lat": 38.7,
        "lng": -9.1,
        "base_capacity_pct": 25,
        "base_workload_count": 112,
    },
    {
        "id": "edge-eu-balkans",
        "display_name": "EU Balkans Edge",
        "city": "Bucharest",
        "region": "Europe",
        "tier": "regional",
        "lat": 44.4,
        "lng": 26.1,
        "base_capacity_pct": 29,
        "base_workload_count": 156,
    },
    # Asia Pacific + Middle East + Africa
    {
        "id": "edge-apac-sg",
        "display_name": "APAC Singapore Edge",
        "city": "Singapore",
        "region": "Asia Pacific",
        "tier": "regional",
        "lat": 1.4,
        "lng": 103.8,
        "base_capacity_pct": 58,
        "base_workload_count": 389,
    },
    {
        "id": "edge-apac-in",
        "display_name": "APAC India Edge",
        "city": "Mumbai",
        "region": "Asia Pacific",
        "tier": "regional",
        "lat": 19.1,
        "lng": 72.9,
        "base_capacity_pct": 47,
        "base_workload_count": 312,
    },
    {
        "id": "edge-apac-kr",
        "display_name": "APAC Korea Edge",
        "city": "Seoul",
        "region": "Asia Pacific",
        "tier": "regional",
        "lat": 37.6,
        "lng": 127.0,
        "base_capacity_pct": 53,
        "base_workload_count": 356,
    },
    {
        "id": "edge-apac-cn",
        "display_name": "APAC China Edge",
        "city": "Beijing",
        "region": "Asia Pacific",
        "tier": "regional",
        "lat": 39.9,
        "lng": 116.4,
        "base_capacity_pct": 61,
        "base_workload_count": 423,
    },
    {
        "id": "edge-apac-hk",
        "display_name": "APAC Hong Kong Edge",
        "city": "Hong Kong",
        "region": "Asia Pacific",
        "tier": "regional",
        "lat": 22.3,
        "lng": 114.2,
        "base_capacity_pct": 49,
        "base_workload_count": 334,
    },
    {
        "id": "edge-me-gulf",
        "display_name": "Middle East Gulf Edge",
        "city": "Dubai",
        "region": "Middle East & Africa",
        "tier": "regional",
        "lat": 25.2,
        "lng": 55.3,
        "base_capacity_pct": 42,
        "base_workload_count": 278,
    },
    {
        "id": "edge-af-south",
        "display_name": "Africa South Edge",
        "city": "Johannesburg",
        "region": "Middle East & Africa",
        "tier": "regional",
        "lat": -26.2,
        "lng": 28.0,
        "base_capacity_pct": 35,
        "base_workload_count": 198,
    },
]
